### ISSUE TITLE
Use unit test framework for writing nicer looking tests with better diagnostics

### ISSUE THREAD

**Issue by Zalastax** [BlackEdder/painlessjson#23]
I think https://github.com/nomad-software/dunit looks good. I have found a way to have the unit test framework as a dependency only for the unittest build, and will push a change to the dub.json if you agree to this idea.

**Comment by BlackEdder** [comment]
dunit does look good. Last time I checked though pulling in a testing framework (I used tested) in a library causes all projects build upon the library to also use the framework, so effectively we would be forcing any user of painlessjson to use dunit like reporting as well. It might be good to double check if this is still the case though.

**Comment by kingsleyh** [comment]
just to comment on this - you are right I get DUnit reporting when I use painlessjson in my project whether I want it or not - in my case I decided to use DUnit as well so it's fine - but I think in general the decision on which test framework to use should be down to the user rather than being forced to use it because of using a particular json library.
